# Generated by Django 5.0 on 2025-12-30 07:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttackerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, unique=True)),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('total_connections', models.PositiveIntegerField(default=0)),
                ('total_login_attempts', models.PositiveIntegerField(default=0)),
                ('total_commands', models.PositiveIntegerField(default=0)),
                ('total_files', models.PositiveIntegerField(default=0)),
                ('threat_level', models.CharField(choices=[('LOW', 'Low Threat'), ('MEDIUM', 'Medium Threat'), ('HIGH', 'High Threat'), ('CRITICAL', 'Critical Threat')], default='LOW', max_length=20)),
                ('threat_score', models.FloatField(default=0.0)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('isp', models.CharField(blank=True, max_length=200, null=True)),
                ('attack_types', models.JSONField(blank=True, default=list)),
                ('targeted_services', models.JSONField(blank=True, default=list)),
                ('is_known_attacker', models.BooleanField(default=False)),
                ('reputation_sources', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-threat_score'],
            },
        ),
        migrations.CreateModel(
            name='HoneypotService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SSH', 'SSH Honeypot'), ('FTP', 'FTP Honeypot'), ('HTTP', 'HTTP Honeypot'), ('TELNET', 'Telnet Honeypot'), ('SMB', 'SMB Honeypot')], max_length=50, unique=True)),
                ('port', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('STOPPED', 'Stopped'), ('ERROR', 'Error')], default='STOPPED', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('total_connections', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Honeypot Service',
                'verbose_name_plural': 'Honeypot Services',
            },
        ),
        migrations.CreateModel(
            name='IPBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, unique=True)),
                ('reason', models.CharField(choices=[('BRUTE_FORCE', 'Brute Force Attack'), ('MALWARE', 'Malware Upload'), ('ABUSE', 'Excessive Abuse'), ('MANUAL', 'Manually Blacklisted'), ('REPUTATION', 'Known Bad Reputation')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_permanent', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'IP Blacklist Entry',
                'verbose_name_plural': 'IP Blacklist Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('port', models.PositiveIntegerField()),
                ('protocol', models.CharField(choices=[('SSH', 'SSH'), ('FTP', 'FTP'), ('HTTP', 'HTTP'), ('TELNET', 'Telnet'), ('SMB', 'SMB'), ('UNKNOWN', 'Unknown')], max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('isp', models.CharField(blank=True, max_length=200, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('raw_data', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address', 'timestamp'], name='dashboard_c_ip_addr_62fbad_idx'), models.Index(fields=['protocol', 'timestamp'], name='dashboard_c_protoco_32b0dc_idx')],
            },
        ),
        migrations.CreateModel(
            name='FileActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('filename', models.CharField(max_length=500)),
                ('filepath', models.CharField(blank=True, max_length=1000, null=True)),
                ('action', models.CharField(choices=[('ACCESS', 'File Access'), ('UPLOAD', 'File Upload'), ('DOWNLOAD', 'File Download'), ('DELETE', 'Delete Attempt'), ('MODIFY', 'Modify Attempt')], max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('file_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_malware', models.BooleanField(default=False)),
                ('malware_name', models.CharField(blank=True, max_length=200, null=True)),
                ('virustotal_result', models.JSONField(blank=True, null=True)),
                ('is_quarantined', models.BooleanField(default=False)),
                ('quarantine_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_activities', to='dashboard.connection')),
            ],
            options={
                'verbose_name_plural': 'File Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('command', models.TextField()),
                ('service', models.CharField(choices=[('SSH', 'SSH'), ('TELNET', 'Telnet'), ('FTP', 'FTP'), ('HTTP', 'HTTP')], max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20)),
                ('attack_type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_malicious', models.BooleanField(default=False)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='dashboard.connection')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address', 'timestamp'], name='dashboard_c_ip_addr_237963_idx'), models.Index(fields=['risk_level'], name='dashboard_c_risk_le_1aa91a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('BRUTE_FORCE', 'Brute Force Attack'), ('SQL_INJECTION', 'SQL Injection'), ('XSS', 'Cross-Site Scripting'), ('MALWARE', 'Malware Upload'), ('PORT_SCAN', 'Port Scanning'), ('ZERO_DAY', 'Potential Zero-Day'), ('ANOMALY', 'Anomaly Detected'), ('RATE_LIMIT', 'Rate Limit Exceeded'), ('BLACKLIST', 'Blacklisted IP')], max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_by', models.CharField(blank=True, max_length=100, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('related_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.connection')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['alert_type', 'timestamp'], name='dashboard_a_alert_t_213b3a_idx'), models.Index(fields=['severity', 'is_acknowledged'], name='dashboard_a_severit_713f4f_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('service', models.CharField(choices=[('SSH', 'SSH'), ('FTP', 'FTP'), ('HTTP', 'HTTP'), ('TELNET', 'Telnet'), ('SMB', 'SMB'), ('ADMIN', 'Admin Panel')], max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('success', models.BooleanField(default=False)),
                ('credential_hash', models.CharField(blank=True, max_length=64)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_attempts', to='dashboard.connection')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address', 'timestamp'], name='dashboard_l_ip_addr_41ac45_idx'), models.Index(fields=['username'], name='dashboard_l_usernam_fe3b9c_idx')],
            },
        ),
    ]
